  const countries = [
    { name: 'USA, New York', timezone: 'America/New_York' },
    { name: 'India, Kolkata', timezone: 'Asia/Kolkata' },
    { name: 'Pakistan, Islamabad', timezone: 'Asia/Kolkata' },
    { name: 'Kazakhstan, Astana', timezone: 'Asia/Kolkata' },
    { name: 'Japan, Tokyo', timezone: 'Asia/Tokyo' },
    { name: 'South Korea, Seoul', timezone: 'Asia/Tokyo' },
    { name: 'UK, London', timezone: 'Europe/London' },
    { name: 'Poland, Warshaw', timezone: 'Europe/Rome' },
    { name: 'Germany, Berlin', timezone: 'Europe/Rome' },
    { name: 'Spain, Madrid', timezone: 'Europe/Rome' },
    { name: 'Denmark, Copenhagen', timezone: 'Europe/Rome' },
    { name: 'France, Paris', timezone: 'Europe/Rome' },
    { name: 'Singapore, Singapore', timezone: 'Asia/Shanghai' },
    { name: 'China, Beijing', timezone: 'Asia/Shanghai' },
    { name: 'Thailand, Bangkok', timezone: 'Asia/Bangkok' },
    { name: 'Australia, Sydney', timezone: 'Australia/Sydney' },
    { name: 'UAE, Abu Dhabi', timezone: 'Asia/Dubai' },
    { name: 'South Africa, Freetown', timezone: 'Africa/Freetown' },
    { name: 'Brazil, Rio de Janeiro', timezone: 'Brazil/East' },
    { name: 'Russia, Moscow', timezone: 'Europe/Moscow' },
    { name: 'Turkey, Ankara', timezone: 'Europe/Moscow' },
  ];
  export default countries
